# MySQL
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'DOG'
  AND NAME LIKE '%el%'
ORDER BY NAME ASC;

# ORACLE
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE UPPER(NAME) LIKE '%EL%'
  AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME ASC;